#-General Properties----------------------------------------------------------------------------------------------------

server:
  port: 9090

#-Gateway Settings------------------------------------------------------------------------------------------------------

spring:
  application:
    name: emlakburada-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9094/auth
  cloud:
    gateway:
      routes:
        - id: emlakburada
          uri: http://localhost:9091
          predicates:
            - Path=/pay/**, /adverts/**, /prepare/**
        - id: emlakburada-payment
          uri: http://localhost:9092
          predicates:
            - Path=/banners/**
            - Method=POST,GET
        - id: emlakburada-advertactivation
          uri: http://localhost:9093
          predicates:
            - Path=/adverts/**
            - Method=POST
        - id: emlakburada-auth
          uri: http://localhost:9094
          predicates:
            - Path=/auth/**
            - Method=POST

#-Other Properties------------------------------------------------------------------------------------------------------

  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive

logging:
  level:
    '[org.springframework.security]': TRACE